# Estágio de Build
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration production

# Estágio de Servidor (Nginx)
FROM nginx:alpine
COPY --from=build /app/dist/frontend /tmp/frontend-dist
RUN cp -r /tmp/frontend-dist/browser/* /usr/share/nginx/html 2>/dev/null || cp -r /tmp/frontend-dist/* /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
