spring.application.name=estoque
server.port=8083

# Configuração da conexão com o banco de dados PostgreSQL (rodando via Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/estoquedb
spring.datasource.username=admin
spring.datasource.password=123

# Configuração do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
