# Configuração Dinâmica para Bancos de Dados na Nuvem (Web)
# Aqui, a aplicação lerá as informações das variáveis de ambiente do seu servidor na Nuvem.
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configuração do Hibernate para o banco em Produção
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
